# TRMNLP configuration
---
watch:
  - .trmnlp.yml
  - src

custom_fields: {}

variables:
  trmnl:
    user:
      name: David
      locale: cs
      time_zone_iana: Europe/Prague
    device:
      battery: 73

  current_date:
    day_name: "Čtvrtek"
    day: 27
    month: "února"
    year: 2026

  nameday: "Alexandr"

  weather:
    temp: 3
    temp_min: -1
    temp_max: 5
    condition: "Oblačno"
    humidity: 65
    wind: 12
    precipitation: 20
    precipitation_mm: 1.2
    pressure: 1013
    icon: "cloudy"
    today_hourly:
      - time: "6"
        temp: 18
        precipitation_mm: 0
      - time: "7"
        temp: 19
        precipitation_mm: 0
      - time: "8"
        temp: 20
        precipitation_mm: 0
      - time: "9"
        temp: 21
        precipitation_mm: 0.2
      - time: "10"
        temp: 22
        precipitation_mm: 0.1
      - time: "11"
        temp: 23
        precipitation_mm: 0
      - time: "12"
        temp: 25
        precipitation_mm: 0.5
      - time: "13"
        temp: 26
        precipitation_mm: 0.3
      - time: "14"
        temp: 27
        precipitation_mm: 0.1
      - time: "15"
        temp: 26
        precipitation_mm: 0.3
      - time: "16"
        temp: 25
        precipitation_mm: 0.2
      - time: "17"
        temp: 24
        precipitation_mm: 0.1
      - time: "18"
        temp: 22
        precipitation_mm: 0.2
      - time: "19"
        temp: 21
        precipitation_mm: 0
      - time: "20"
        temp: 20
        precipitation_mm: 0
      - time: "21"
        temp: 19
        precipitation_mm: 0
      - time: "22"
        temp: 18
        precipitation_mm: 0
      - time: "23"
        temp: 17
        precipitation_mm: 0
      - time: "0"
        temp: 16
        precipitation_mm: 0
      - time: "1"
        temp: 15
        precipitation_mm: 0
      - time: "2"
        temp: 15
        precipitation_mm: 0.1
      - time: "3"
        temp: 14
        precipitation_mm: 0.3
      - time: "4"
        temp: 14
        precipitation_mm: 0.2
      - time: "5"
        temp: 13
        precipitation_mm: 0

  forecast:
    - day: "Pá"
      date: 28
      temp_max: 4
      temp_min: 1
      precipitation: 15
      precipitation_mm: 0.8
      icon: "cloudy"
    - day: "So"
      date: 1
      temp_max: 6
      temp_min: 2
      precipitation: 5
      precipitation_mm: 0.0
      icon: "sunny"
    - day: "Ne"
      date: 2
      temp_max: 3
      temp_min: -1
      precipitation: 60
      precipitation_mm: 4.5
      icon: "rainy"
    - day: "Po"
      date: 3
      temp_max: 5
      temp_min: 0
      precipitation: 10
      precipitation_mm: 0.2
      icon: "sunny"
    - day: "Út"
      date: 4
      temp_max: 4
      temp_min: 1
      precipitation: 20
      precipitation_mm: 1.0
      icon: "cloudy"
    - day: "St"
      date: 5
      temp_max: 7
      temp_min: 3
      precipitation: 5
      precipitation_mm: 0.0
      icon: "sunny"
    - day: "Čt"
      date: 6
      temp_max: 5
      temp_min: 2
      precipitation: 25
      precipitation_mm: 1.5
      icon: "partly_cloudy"

  events_today:
    - time: "10:00"
      title: "Schůzka s Petrem"
    - time: "14:00"
      title: "Doktor - kontrola"
    - time: "16:30"
      title: "Vyzvednutí ze školy"

  events_tomorrow:
    - time: "09:00"
      title: "Dentista"
    - time: "11:00"
      title: "Oběd s rodinou"

  tasks:
    - text: "Nakoupit potraviny"
      done: false
    - text: "Vysávat obývák"
      done: false
    - text: "Prádlo - vyprat"
      done: true
    - text: "Vynést koš"
      done: false
    - text: "Zalít květiny"
      done: false
    - text: "Zavolat mamince"
      done: true

  sensors:
    indoor:
      temp: 22.3
      humidity: 45
      co2: 8888
    outdoor:
      temp: 23.1
      humidity: 78
    rooms:
      - name: "Ložnice"
        temp: 19.8
      - name: "Pracovna"
        temp: 21.1
      - name: "Koupelna"
        temp: 23.5
